
##h2 ??
spring:
  h2:
    console:
      enabled: true
      path : /h2-console
  ## Database ??
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/studycafe
    username: sa
    password:


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    web: info
    sql: error # error: Display when error occur
    org.hibernate: error
    org.springframework: error
    com.chung.security.demo: info

jwt:
  header : Authorization
  #HS512 ????? ??? ??? ??? 512bit, ? 64byte ??? secret key? ???? ??.
  #echo -n 'springboot-studycafe-bysong-project-jwt-security-springboot-studycafe-bysong-project-jwt-security' | base64 ??? ???? base64? ???
  secret : keyc3ByaW5nYm9vdC1zdHVkeWNhZmUtYnlzb25nLXByb2plY3Qtand0LXNlY3VyaXR5LXNwcmluZ2Jvb3Qtc3R1ZHljYWZlLWJ5c29uZy1wcm9qZWN0LWp3dC1zZWN1cml0eQ==
  token-validity-in-seconds: 1800 #?